// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starter_CleanArch_UAA2.Infrastructure.Database;

#nullable disable

namespace Starter_CleanArch_UAA2.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starter_CleanArch_UAA2.Domain.Models.NewsletterSignUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsDayFact")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Day_Fact");

                    b.Property<bool>("IsMonthly")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Monthly");

                    b.Property<bool>("IsNews")
                        .HasColumnType("bit")
                        .HasColumnName("Is_News");

                    b.HasKey("Id")
                        .HasName("PK_Newsletter_Sign_Up");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IDX_Newsletter__Email");

                    b.ToTable("Newsletter_Sign_Up", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
