<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Starter_CleanArch_UAA2.ApplicationCore\Starter_CleanArch_UAA2.ApplicationCore.csproj" />
    <ProjectReference Include="..\Starter_CleanArch_UAA2.Domain\Starter_CleanArch_UAA2.Domain.csproj" />
    <ProjectReference Include="..\Starter_CleanArch_UAA2.Infrastructure.Database\Starter_CleanArch_UAA2.Infrastructure.Database.csproj" />
  </ItemGroup>

</Project>
