<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.46" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Starter_CleanArch_UAA2.ApplicationCore\Starter_CleanArch_UAA2.ApplicationCore.csproj" />
    <ProjectReference Include="..\Starter_CleanArch_UAA2.Domain\Starter_CleanArch_UAA2.Domain.csproj" />
    <ProjectReference Include="..\Starter_CleanArch_UAA2.Infrastructure.Database\Starter_CleanArch_UAA2.Infrastructure.Database.csproj" />
    <ProjectReference Include="..\Starter_CleanArch_UAA2.Infrastructure.Mailer\Starter_CleanArch_UAA2.Infrastructure.Mailer.csproj" />
  </ItemGroup>

</Project>
